/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabManuRequest;

import Business.Ecosystem;
import Business.Items.Item;
import Business.Manufacturer.Manufacturer;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srushtidesai
 */
public class orderItemsManu extends javax.swing.JPanel {

    /**
     * Creates new form orderItemsManu
     */
    JPanel CardLayoutJPanel;
    UserAccount account;
    Ecosystem business;
    Manufacturer manu;
    String manuId;
    public orderItemsManu(JPanel CardLayoutJPanel, UserAccount account, Ecosystem business, String manuId) {
        initComponents();
        this.CardLayoutJPanel=CardLayoutJPanel;
        this.account=account;
        this.business= business;
        this.manuId=manuId;
        populatetable();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manuTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(manuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 375, 275));

        itemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(itemtable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 360, 280));

        jButton1.setText("View Items");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        populatetable1();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable itemtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable manuTable;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        
        ArrayList<Manufacturer> manuList = business.getManufacturerDirectory().getManufacturerList();
    
        int rowCount = manuTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)manuTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Manufacturer m: manuList)
        {
            Object row[] = new Object[6];
            row[0] = m.getManuId();
            row[1] = m.getManuName();
            row[2] = m.getPhoneNumber();
            row[3] = m.getEmailAddress();
            model.addRow(row);
        
        }
    }

    private void populatetable1() {
        DefaultTableModel menuModel = (DefaultTableModel) itemtable.getModel();
        menuModel.setRowCount(0);
       
        for(Item i : manu.getItemDirectory())
        {
            
           
                Object [] row = new Object[3];
                row[0] = i.getItemName();
                row[1] = i.getQuantity();
                row[2] = i.getPrice();
              

                menuModel.addRow(row);
            
        }
    }
}
