/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Lab;

import Business.Ecosystem;
import Business.Manufacturer.Manufacturer;
import Business.UserAccount.UserAccount;
import UserInterface.LabManuRequest.orderItemsManu;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrutikasalian
 */
public class LabOrderAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabOrderAreaJPanel
     */
    JPanel CardLayoutJPanel;
    UserAccount account;
    Ecosystem business;
    String manuId;
    public LabOrderAreaJPanel(JPanel CardLayoutJPanel, UserAccount account, Ecosystem business) {
        initComponents();
        this.CardLayoutJPanel=CardLayoutJPanel;
        this.account=account;
        this.business= business;
        populateOrderDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderList = new javax.swing.JTable();

        setBackground(new java.awt.Color(138, 194, 211));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        requestTestJButton.setText("Place New Order");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 400, 190, 40));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jButton1.setText("Order Details");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 460, 190, 40));

        refreshTestJButton.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        refreshTestJButton.setText("Refresh");
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 349, 190, 40));

        tblOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Manufacturer ID", "Manufacturer Name", "Contact", "Email Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrderList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 560, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        // TODO add your handling code here:
        int row = tblOrderList.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
          
           String manuId;
           manuId= (String) tblOrderList.getValueAt(row, 0);
                
                 orderItemsManu oim =new orderItemsManu (CardLayoutJPanel,account,business,manuId);
                 CardLayoutJPanel.add("UpdateStatusPanel",oim);
                 CardLayout layout=(CardLayout)CardLayoutJPanel.getLayout();
                 layout.next(CardLayoutJPanel);
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTable tblOrderList;
    // End of variables declaration//GEN-END:variables

    private void populateOrderDetails() {
        ArrayList<Manufacturer> manuList = business.getManufacturerDirectory().getManufacturerList();
    
        int rowCount = tblOrderList.getRowCount();
        DefaultTableModel model = (DefaultTableModel)tblOrderList.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Manufacturer m: manuList) {
            Object row[] = new Object[6];
            row[0] = m.getManuId();
            row[1] = m.getManuName();
            row[2] = m.getPhoneNumber();
            row[3] = m.getEmailAddress();
           
           
           
            
            model.addRow(row);
        }
    }
 }
