/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Rooms;

import Business.Hospital.Hospital;
import Business.Rooms.Rooms;
import javax.swing.JPanel;

/**
 *
 * @author shrutikasalian
 */
public class UpdateRoom extends javax.swing.JPanel {

    /**
     * Creates new form UpdateRoom
     */
    JPanel CardLayoutJPanel;
    int viewRoom;
    Hospital hospital;
    Rooms s;
    public UpdateRoom(JPanel CardLayoutJPanel, int viewRoom, Hospital hospital) {
        initComponents();
        this.CardLayoutJPanel=CardLayoutJPanel;
        this.viewRoom=viewRoom;
        s = hospital.roomId(viewRoom);
        if(s!=null){
            TxtUpdate.setText(String.valueOf(s.getRoomQuantity()));
            RoomStatus.setText(s.getRoomStatus());
        }
            
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        TxtUpdate = new javax.swing.JTextField();
        UpdateSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RoomStatus = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Update Rooms:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, 30));

        TxtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUpdateActionPerformed(evt);
            }
        });
        add(TxtUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 160, -1));

        UpdateSave.setBackground(new java.awt.Color(255, 255, 255));
        UpdateSave.setText("Save");
        UpdateSave.setEnabled(false);
        UpdateSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSaveActionPerformed(evt);
            }
        });
        add(UpdateSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 80, -1));

        jLabel1.setText("Room Status:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 30));
        add(RoomStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 160, -1));

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUpdateActionPerformed

    private void UpdateSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSaveActionPerformed
        s.setRoomQuantity(Integer.parseInt(TxtUpdate.getText()));
        s.setRoomStatus(RoomStatus.getText());
    }//GEN-LAST:event_UpdateSaveActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        TxtUpdate.setEditable(true);
        RoomStatus.setEditable(true);
        UpdateSave.setEnabled(true);
    }//GEN-LAST:event_UpdateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RoomStatus;
    private javax.swing.JTextField TxtUpdate;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton UpdateSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
