/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Lab;

import Business.Ecosystem;
import Business.Manufacturer.Manufacturer;
import Business.UserAccount.UserAccount;
import UserInterface.LabManuRequest.orderItemsManu;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srushtidesai
 */
public class LabOrderAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabOrderAreaJPanel
     */
    JPanel CardLayoutJPanel;
    UserAccount account;
    Ecosystem business;
    String manuId;
    public LabOrderAreaJPanel(JPanel CardLayoutJPanel, UserAccount account, Ecosystem business) {
        initComponents();
        this.CardLayoutJPanel=CardLayoutJPanel;
        this.account=account;
        this.business= business;
        populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manuTable = new javax.swing.JTable();
        requestTestJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Lab Name", "Status", "Order Time", "Manufacturer Name", "Delivery Time"
            }
        ));
        jScrollPane1.setViewportView(manuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 87, 742, 242));

        requestTestJButton.setText("Place New Order");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 347, -1, -1));

        jButton1.setText("Order Details");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 347, -1, -1));

        refreshTestJButton.setText("Refresh");
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 24, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        // TODO add your handling code here:
        orderItemsManu otm = new orderItemsManu(CardLayoutJPanel, account, business,manuId);
        CardLayoutJPanel.add("LabOrderAreaJPanel", otm);
        CardLayout layout = (CardLayout)CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel); 
    }//GEN-LAST:event_requestTestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manuTable;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        ArrayList<Manufacturer> manuList = business.getManufacturerDirectory().getManufacturerList();
        
        int rowCount = manuTable.getRowCount();
        manuId=(String) manuTable.getValueAt(rowCount,0);
        DefaultTableModel model = (DefaultTableModel)manuTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Manufacturer m: manuList) {
            Object row[] = new Object[6];
            row[0] = m.getManuId();
            row[1] = m.getManuName();
            row[2] = m.getPhoneNumber();
            row[3] = m.getEmailAddress();
            model.addRow(row);
        }
    }
}
