/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Ecosystem;
import Business.Manufacturer.Manufacturer;
import Business.UserAccount.UserAccount;
import UserInterface.Manufacturer.ViewManufacturer;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srushtidesai
 */
public class SystemAdminManufacturerNewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminManufacturerNewJPanel
     */
    JPanel CardLayoutJPanel;
    Ecosystem business;
    Manufacturer manufacturer;
    UserAccount useraccount;
    public SystemAdminManufacturerNewJPanel(JPanel CardLayoutJPanel,Ecosystem business,UserAccount useraccount) {
        initComponents();
        this.CardLayoutJPanel =CardLayoutJPanel;
        this.business = business;
        this.useraccount=useraccount;
        this.manufacturer=(Manufacturer) this.useraccount.getDetails();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manuTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(138, 194, 211));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Manufacturer ID", "Manufacturer Name", "Phone Number", "Email Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 771, 230));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE MANUFACTURER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 200, 44));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jButton2.setText("View ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 200, 43));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jButton3.setText("Refresh");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 200, 41));

        jButton4.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 200, 42));

        backBtn.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        backBtn.setText("<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 50, -1));

        jLabel2.setBackground(new java.awt.Color(138, 194, 211));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Picture/cover1.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1180, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddManufacturerJPanel addmanu = new AddManufacturerJPanel(CardLayoutJPanel, business,useraccount);
        CardLayoutJPanel.add("AddManufacturerJPanel", addmanu);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int row = manuTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        System.out.println("=========== >> " + manuTable.getValueAt(row, 0));
        String viewManu;
        viewManu = (String) manuTable.getValueAt(row, 0);
        System.out.println(viewManu);
        ViewManufacturer  viewManufacturer= new ViewManufacturer(CardLayoutJPanel,business, viewManu);
        CardLayoutJPanel.add(" ViewManufacturer", viewManufacturer);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i = manuTable.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
        String delManu;
        delManu = (String) manuTable.getValueAt(i, 0);
        System.out.println(delManu);
        business.getManufacturerDirectory().removeManufacturer(delManu);
        populateTable();
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.previous(CardLayoutJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manuTable;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        ArrayList<Manufacturer> manuList = business.getManufacturerDirectory().getManufacturerList();
    
        int rowCount = manuTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)manuTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Manufacturer m: manuList) {
            Object row[] = new Object[6];
            row[0] = m.getManuId();
            row[1] = m.getManuName();
            row[2] = m.getPhoneNumber();
            row[3] = m.getEmailAddress();
           
           
           
            
            model.addRow(row);
        }
    }
}
