/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Ambulance.Ambulance;
import Business.Ambulance.AmbulanceFleet;
import Business.Ecosystem;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import UserInterface.Ambulance.CreateAmbulanceJPanel;
import java.awt.CardLayout;
import static java.time.InstantSource.system;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrutikasalian
 */
public class PatientSOSJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientSOSJPanel
     */
    private JPanel CardLayoutJPanel;
    private Ecosystem business;
    private UserAccount useraccount;
    Patient patient;
    Ambulance ambulance;
   
    
    AmbulanceFleet amb;
    public PatientSOSJPanel(JPanel CardLayoutJPanel, Ecosystem business,UserAccount useraccount,Patient patient) {
        initComponents();
        this.CardLayoutJPanel = CardLayoutJPanel;
        this.business = business;
        this.useraccount=useraccount;
        this.patient=patient;
       // this.ambulance=ambulance;
        
        populateTable();

    }
    public void populateTable() {
        
        ArrayList<Ambulance> sosList = business.getAmbulancefleet().getAmbulanceFleet();
        int rowCount = sosTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)sosTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Ambulance sos : sosList) {
            Object row[] = new Object[6];
            row[0] = sos.getAmbulanceId();
            row[1] = sos.getDriverName();
            row[2] = sos.getPhoneNo();
            row[3] = sos.getBaseLocation();
            row[4] = sos.getLicenseNo();
            row[5] = sos.getReqStatus();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sosTable = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();
        BookSOSbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(138, 194, 211));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REQUEST FOR SOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 86, -1, -1));

        backBtn.setText("<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 592, -1, -1));

        sosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ambulance Id", "Driver Name", "Contact Number", "Base Location", "License Number", "Status"
            }
        ));
        jScrollPane1.setViewportView(sosTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 133, 640, 260));

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 92, -1, -1));

        BookSOSbtn.setText("SEND REQUEST FOR AMBULANCE");
        BookSOSbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookSOSbtnActionPerformed(evt);
            }
        });
        add(BookSOSbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 411, 263, 62));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 121, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.previous(CardLayoutJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void BookSOSbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookSOSbtnActionPerformed
        // TODO add your handling code here:
        int row = sosTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null,
                    "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
           // Ambulance ambulance1 = (Ambulance)sosTable.getValueAt(row, 0);
           ArrayList<Ambulance> ambulanceList = business.getAmbulancefleet().getAmbulanceFleet();
           String bookSOS;
           bookSOS= (String) sosTable.getValueAt(row, 0);
                
                 ConfirmSOSRequest csr=new ConfirmSOSRequest(CardLayoutJPanel,useraccount,business, patient, bookSOS);
                 CardLayoutJPanel.add("MenuPanel",csr);
                 CardLayout layout=(CardLayout)CardLayoutJPanel.getLayout();
                 layout.next(CardLayoutJPanel);
        }
        
        /*ArrayList<Ambulance> ambulanceList = business.getAmbulancefleet().getAmbulanceFleet();
        String bookSOS;
        bookSOS= (String) sosTable.getValueAt(row, 0);
        System.out.println(bookSOS);
        for(Ambulance ambu: ambulanceList )
        {
            if(ambu.getAmbulanceId().equalsIgnoreCase(bookSOS)){
                
               String address=patientAddr.getText();
               ambulance.addSOSReq(ambu.getAmbulanceId(), ambu.getPhoneNo(), patient.getName(),address ,ambu.getBaseLocation());
               JOptionPane.showMessageDialog(null, "AMBULANCE REQUEST SENT");
        
        }     
            
        }
        
        /*ambulance.addOrder(restaurant.getName(), userAccount.getUsername(), null, items, String.valueOf(sum) , address);
        for(Customer cust:ecosystem.getCustomerDirectory().getCustomerDirectory()){
            if(userAccount.getUsername().equals(cust.getUserName())){
                cust.addOrder(restaurant.getName(), userAccount.getUsername(), null, items, String.valueOf(sum) , address);
                JOptionPane.showMessageDialog(null, "You Order placed successfully");
            }
        }  */   
        
        
        
    }   
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
        
       
    }//GEN-LAST:event_BookSOSbtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookSOSbtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable sosTable;
    // End of variables declaration//GEN-END:variables
}

